FROM node:20 AS build
WORKDIR /app
RUN npm install -g yarn && yarn config set strict-ssl false
COPY package.json yarn.lock ./
RUN yarn config set registry https://registry.npmmirror.com && yarn install --frozen-lockfile
COPY . .
ARG VITE_API_BASE_URL=/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN yarn build

FROM nginx:alpine
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /app
EXPOSE 5173
